pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        addBadge(icon: 'green.gif', text: 'Build Stage')
      }
    }
    stage('Stage1') {
        steps {
            echo 'Stage1 - Resize Primary'
        }
    }
    stage('Stage2') {
        steps {
            addBadge(icon: 'error.gif', text: 'Replace primary transit gateway')

            echo 'Stage1 - Resize Primary'
        }
    }
    stage('CI') {
      steps {
        createSummary(text: "hello.....:${env.BUILD_URL}", icon: 'green.gif')
      }
    }
    stage('Report') {
      steps {
        addInfoBadge(text: 'Buildsummary', id: 'text', link: 'http://localhost:8080/job/badgetest/')
        echo 'Stage1 - Resize Primary'
      }
    }
  }
}