pipeline {
    agent any
    environment {
        PROJECT_NAME = "ngraph"
        BRANCH_NAME = "${env.BRANCH_NAME}".replace("/", "%2F")
        buildno = null
        build_res = ""
        version = "4.5.6"
    }
  stages {
    stage('Build') {
      steps {
        addBadge(icon: 'green.gif', text: 'Build Stage')
      }
    }
    stage('Stage1') {
        steps {
            echo 'Stage1 - Resize Primary'
        }
    }
    stage('Stage2') {
        steps {
            addBadge(icon: 'error.gif', text: 'Replace primary transit gateway')

            echo 'Stage1 - Resize Primary'
        }
    }
    stage('CI') {
      steps {
          echo "--------${BRANCH_NAME}"
        createSummary(text:'${BRANCH_NAME}', icon: 'green.gif')
      }
    }
    stage('Report') {
      steps {
        addInfoBadge(text: 'Buildsummary', id: 'text', link: 'http://localhost:8080/job/badgetest/')
        echo 'Stage1 - Resize Primary'
      }
    }
  }
}